# Generated by Django 2.0.4 on 2018-05-14 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('puput', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoEntryPage',
            fields=[
                ('entrypage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puput.EntryPage')),
                ('video_url', models.URLField()),
                ('activity_price', models.CharField(blank=True, max_length=500, verbose_name='Activity price')),
            ],
            options={
                'abstract': False,
            },
            bases=('puput.entrypage',),
        ),
        migrations.RemoveField(
            model_name='videoentrypage2',
            name='entrypage_ptr',
        ),
        migrations.DeleteModel(
            name='VideoEntryPage2',
        ),
    ]
