# Generated by Django 2.0.4 on 2018-05-15 16:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0040_page_draft_title'),
        ('wagtailforms', '0003_capitalizeverbose'),
        ('wagtailimages', '0019_delete_filter'),
        ('wagtailredirects', '0005_capitalizeverbose'),
        ('puput', '0002_auto_20180514_1147'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityEntryPage',
            fields=[
                ('entrypage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='puput.EntryPage')),
                ('price', models.CharField(blank=True, max_length=500, verbose_name='Price in eur')),
                ('address', models.CharField(blank=True, max_length=500, verbose_name='Activity price')),
                ('features', models.CharField(blank=True, max_length=500, verbose_name='Features (separate with comma)')),
                ('image1', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image 1 (size 480x350)')),
                ('image2', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image 2 (size 480x350)')),
                ('image3', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image 3 (size 480x350)')),
                ('image4', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image 4 (size 480x350)')),
            ],
            options={
                'abstract': False,
            },
            bases=('puput.entrypage',),
        ),
        migrations.RemoveField(
            model_name='videoentrypage',
            name='entrypage_ptr',
        ),
        migrations.DeleteModel(
            name='VideoEntryPage',
        ),
    ]
