# Generated by Django 2.0.4 on 2018-05-15 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('puput', '0003_auto_20180515_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activityentrypage',
            name='address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Address'),
        ),
    ]
